# ============================================================================
# Cloud Build Configuration - Using Docker
# ============================================================================
# Builds Docker image using Dockerfile
# Then deploys to Cloud Run
# ============================================================================

steps:
  # ========================================================================
  # Step 1: Build Docker image and push to Container Registry
  # ========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-and-push'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pgadmin-api:latest'
      - '.'

  # ========================================================================
  # Step 2: Push image to Container Registry
  # ========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'

  # ========================================================================
  # Step 3: Deploy to Cloud Run
  # ========================================================================
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    id: 'deploy-to-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pgadmin-api'
      - '--image=gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=3600'
      - '--add-cloudsql-instances=pgadmin-481518:us-central1:pgadmin-db'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=DEBUG=False'
      - '--set-env-vars=DATABASE_NAME=pgadmin_production'
      - '--set-env-vars=DATABASE_USER=pgadmin_user'
      - '--set-secrets=DATABASE_PASSWORD=db-password:latest'
      - '--set-secrets=SECRET_KEY=django-secret-key:latest'
      - '--set-env-vars=DATABASE_SOCKET=/cloudsql/pgadmin-481518:us-central1:pgadmin-db'

  # Migrations now run at container startup via scripts/start.sh

# ============================================================================
# Build Options
# ============================================================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# ============================================================================
# Push images to Container Registry
# ============================================================================
images:
  - 'gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/pgadmin-api:latest'

# ============================================================================
# Build timeout
# ============================================================================
timeout: '3600s'

# ============================================================================
# Build timeout
# ============================================================================
timeout: '3600s'
