# ============================================================================
# Cloud Build Configuration - Simple & Reliable
# ============================================================================
# Uses Google Cloud Buildpacks to build Docker image from source
# Then deploys to Cloud Run
# ============================================================================

steps:
  # ========================================================================
  # Step 1: Deploy to Cloud Run with Buildpacks (simplest approach)
  # ========================================================================
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    id: 'deploy-to-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pgadmin-api'
      - '--source=.'
      - '--platform=managed'
      - '--region=us-central1'
      - '--no-allow-unauthenticated'
      - '--port=8000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=3600'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=DEBUG=False'
      - '--set-env-vars=DATABASE_NAME=pgadmin_production'
      - '--set-env-vars=DATABASE_USER=pgadmin_user'
      - '--set-secrets=DATABASE_PASSWORD=db-password:latest'
      - '--set-secrets=SECRET_KEY=django-secret-key:latest'
      - '--set-secrets=DATABASE_HOST=database-host:latest'

  # ========================================================================
  # Step 2: Allow public access to Cloud Run service
  # ========================================================================
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    id: 'make-public'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services add-iam-policy-binding pgadmin-api \
          --region=us-central1 \
          --member=allUsers \
          --role=roles/run.invoker || true
    allowFailure: true

  # ========================================================================
  # Step 3: Run Database Migrations (optional, allowed to fail)
  # ========================================================================
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    id: 'run-migrations'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'pgadmin-migrate-$BUILD_ID'
      - '--image=gcr.io/$PROJECT_ID/pgadmin-api'
      - '--region=us-central1'
      - '--tasks=1'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=DEBUG=False'
      - '--set-env-vars=DATABASE_NAME=pgadmin_production'
      - '--set-env-vars=DATABASE_USER=pgadmin_user'
      - '--set-secrets=DATABASE_PASSWORD=db-password:latest'
      - '--set-secrets=SECRET_KEY=django-secret-key:latest'
      - '--set-secrets=DATABASE_HOST=database-host:latest'
      - '--execute-now'
    allowFailure: true

# ============================================================================
# Build Options
# ============================================================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# ============================================================================
# Build timeout
# ============================================================================
timeout: '3600s'
