# ============================================================================
# Cloud Build Configuration - Simple & Reliable
# ============================================================================
# Uses Google Cloud Buildpacks to build Docker image from source
# Then deploys to Cloud Run
# ============================================================================

steps:
  # ========================================================================
  # Step 1: Build Docker image using Cloud Buildpacks
  # ========================================================================
  - name: 'gcr.io/cloud-builders/pack'
    id: 'build-image'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # ========================================================================
  # Step 2: Tag image as latest
  # ========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-image'
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'
      - 'gcr.io/$PROJECT_ID/pgadmin-api:latest'

  # ========================================================================
  # Step 3: Deploy to Cloud Run
  # ========================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-to-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'pgadmin-api'
      - '--image=gcr.io/$PROJECT_ID/pgadmin-api:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=3600'
      - '--quiet'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=DEBUG=False'
      - '--set-env-vars=DATABASE_NAME=pgadmin_production'
      - '--set-env-vars=DATABASE_USER=pgadmin_user'
      - '--set-secrets=DATABASE_PASSWORD=db-password:latest'
      - '--set-secrets=SECRET_KEY=django-secret-key:latest'
      - '--set-secrets=DATABASE_HOST=database-host:latest'

  # ========================================================================
  # Step 4: Run Database Migrations (optional, allowed to fail)
  # ========================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-migrations'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'pgadmin-migrate-$BUILD_ID'
      - '--image=gcr.io/$PROJECT_ID/pgadmin-api:latest'
      - '--region=us-central1'
      - '--tasks=1'
      - '--set-env-vars=ENVIRONMENT=production'
      - '--set-env-vars=DEBUG=False'
      - '--set-env-vars=DATABASE_NAME=pgadmin_production'
      - '--set-env-vars=DATABASE_USER=pgadmin_user'
      - '--set-secrets=DATABASE_PASSWORD=db-password:latest'
      - '--set-secrets=SECRET_KEY=django-secret-key:latest'
      - '--set-secrets=DATABASE_HOST=database-host:latest'
      - '--execute-now'
    allowFailure: true

# ============================================================================
# Build Options
# ============================================================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# ============================================================================
# Push images to Container Registry
# ============================================================================
images:
  - 'gcr.io/$PROJECT_ID/pgadmin-api:latest'
  - 'gcr.io/$PROJECT_ID/pgadmin-api:$SHORT_SHA'

# ============================================================================
# Build timeout
# ============================================================================
timeout: '3600s'
