# Generated by Django 4.2.7 on 2025-12-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('bed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('expense_date', models.DateTimeField()),
                ('paid_by', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=50, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_level', models.IntegerField()),
                ('floor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['property', 'floor_level'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=50)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField(default=False)),
                ('occupied_since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Occupancies',
                'ordering': ['property', 'floor', 'room', 'bed'],
            },
        ),
        migrations.CreateModel(
            name='OccupancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('occupied', 'Occupied'), ('freed', 'Freed')], max_length=20)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Occupancy Histories',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('floors_count', models.IntegerField(default=5)),
                ('rooms_per_floor', models.IntegerField(default=2)),
                ('beds_per_room', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_beds', models.IntegerField(default=1)),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('dormitory', 'Dormitory')], max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.floor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'ordering': ['floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly')], default='monthly', max_length=20)),
                ('joining_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('next_pay_date', models.DateField()),
                ('payment_cycle_start', models.DateField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('aadhar_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('override_comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_resident', to='properties.bed')),
                ('current_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_residents_floor', to='properties.floor')),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_residents_room', to='properties.room')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active'], name='properties__is_acti_78cc81_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.resident'),
        ),
        migrations.AddField(
            model_name='occupancyhistory',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_histories', to='properties.bed'),
        ),
        migrations.AddField(
            model_name='occupancyhistory',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_histories', to='properties.floor'),
        ),
        migrations.AddField(
            model_name='occupancyhistory',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_histories', to='properties.property'),
        ),
        migrations.AddField(
            model_name='occupancyhistory',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_histories', to='properties.resident'),
        ),
        migrations.AddField(
            model_name='occupancyhistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_histories', to='properties.room'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='bed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy', to='properties.bed'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.floor'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.property'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupancies', to='properties.resident'),
        ),
        migrations.AddField(
            model_name='occupancy',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.room'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='properties.property'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='properties.resident'),
        ),
        migrations.AddField(
            model_name='floor',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.property'),
        ),
        migrations.AddField(
            model_name='expense',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property'),
        ),
        migrations.AddField(
            model_name='bed',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.floor'),
        ),
        migrations.AddField(
            model_name='bed',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.property'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.room'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='properties__usernam_e489c2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='properties__email_6cf314_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='properties__role_4dbbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor', 'room_number'], name='properties__floor_i_ff973e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property'], name='properties__propert_81b02f_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active'], name='properties__is_acti_07fce0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['property'], name='properties__propert_a821d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['mobile'], name='properties__mobile_42019d_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['next_pay_date'], name='properties__next_pa_80e39e_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['is_active'], name='properties__is_acti_101904_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['-created_at'], name='properties__created_ec1416_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['property', 'resident'], name='properties__propert_7a5920_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['resident', '-payment_date'], name='properties__residen_214c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='properties__payment_f05444_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancyhistory',
            index=models.Index(fields=['property', 'resident'], name='properties__propert_d203f3_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancyhistory',
            index=models.Index(fields=['resident', '-action_date'], name='properties__residen_70a159_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancyhistory',
            index=models.Index(fields=['action', '-action_date'], name='properties__action_1d6152_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['property', 'is_occupied'], name='properties__propert_dd0c62_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['resident'], name='properties__residen_31305d_idx'),
        ),
        migrations.AddIndex(
            model_name='occupancy',
            index=models.Index(fields=['is_occupied'], name='properties__is_occu_a25db2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['property', 'status'], name='properties__propert_ccf6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['priority', '-reported_date'], name='properties__priorit_993b02_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='properties__status_19b210_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['property', 'floor_level'], name='properties__propert_da4352_idx'),
        ),
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['is_active'], name='properties__is_acti_3e69da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('property', 'floor_level')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['property', 'category'], name='properties__propert_f46c04_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-expense_date'], name='properties__expense_ab8e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['amount'], name='properties__amount_e7d33c_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['room', 'bed_number'], name='properties__room_id_cc3715_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['property'], name='properties__propert_eec7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['is_active'], name='properties__is_acti_b7112e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
    ]
